name: Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x, 18.x ]

    steps:
      - name: checkout main branch
        uses: actions/checkout@v3


      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install node modules
        run: yarn install
        env:
          CI: true

      - name: lint code
        run: yarn lint
        env:
          CI: true
  
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x, 18.x ]

    steps:
      - name: checkout main branch
        uses: actions/checkout@v3


      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install node modules
        run: yarn install
        env:
          CI: true

      - name: build code
        run: yarn build
        env:
          CI: true
